config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'creatures/index'
  get 'creatures/show'
  get 'creatures/search', to: 'creatures#search'
  get 'creatures/shsp', to: 'creatures#search_species'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :creatures, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:create, :show, :new]
  end
  resources :bookings, only: [:index, :destroy, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :creature
end

app/models/creature.rb
class Creature < ApplicationRecord
  has_one_attached :profile_pic
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :creatures, dependent: :destroy
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    @bookings = Booking.where(user: current_user)
    @creatures = policy_scope(Creature).order(created_at: :desc)
    @creatures = Creature.where(user: current_user)
  end

  def show
    @creature = Creature.find(params[:creature_id])
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @creature = Creature.find(params[:creature_id])
    @booking = Booking.new
    authorize @booking
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to root_path
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @creature = Creature.find(params[:creature_id])
    @booking.creature = @creature
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render 'creatures/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :price)
  end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = policy_scope(Creature).order(created_at: :desc)
    if params[:query].present?
      @creatures = Creature.near(params[:query], 4)
    else
      @creatures = Creature.all
    end
    map
  end

  def show
    @creature = Creature.find(params[:id])
    @markers = [{
        lat: @creature.latitude,
        lng: @creature.longitude,
        info_window: render_to_string(partial: "info_window", locals: { creature: @creature })
      }]
    @booking = Booking.new(creature: @creature)
    authorize @creature
  end

  def search
    @creatures = Creature.where(power: params[:power])
    authorize @creatures
    map
  end

  def search_species
    @creatures = Creature.where(species: params[:species])
    authorize @creatures
    map
  end

  def new
    @user = current_user
    @creature = Creature.new
    authorize @creature
  end

  def create
    @user = current_user
    @creature = Creature.new(creature_params)
    @creature.user = @user
    if @creature.save
      redirect_to bookings_path
    else
      render :new
    end
    authorize @creature
  end

  def destroy
    @creature = Creature.find(params[:id])
    authorize @creature
    @creature.destroy
    redirect_to bookings_path
  end

  private

  def creature_params
    params.require(:creature).permit(:name, :type, :address, :power, :age, :description, :price_per_day, :profile_pic)
  end

  def map
    @markers = @creatures.geocoded.map do |creature|
      {
        lat: creature.latitude,
        lng: creature.longitude,
        info_window: render_to_string(partial: "info_window", locals: { creature: creature })
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
    @sample_creature = Creature.first(4)
  end

  def index
    @creatures = Creature.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<div class="page">
  <div class="category">
    <div>
      <h2 class="my-4">Edit your experience with <%= @booking.creature.name %></h2>
      <div class="two-columns-page">
        <div class="left-block">
          <div class="card-product" style="height: 140px;">
            <%= image_tag @booking.creature.profile_pic, :style => "height: 100%; width: 140px;" %>
            <div class="card-product-infos">
              <h2><%= @booking.creature.name %> the <%= @booking.creature.species %></h2>
              <p><%= @booking.creature.description %></p>
              <p style="opacity: 0;">.</p>
              <div class="bottom" style="display:flex; justify-content: space-between;">
                <p><%= @booking.creature.rating %> ⭐️</p>
                <p id="creature_price"><%= @booking.creature.price_per_day %>$ <small>per day</small></p>
              </div>
            </div>
          </div>
          <div id="map"
                  class="my-4"
                  style="width: 600px; height: 400px; border-radius: 7px;"
                  data-markers="<%= @markers.to_json %>"
                  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          </div>
        <div class="right-block">
          <div>
            <% if policy(@booking).new? %>
              <%= simple_form_for [@booking.creature, @booking] do |f| %>
                <%= f.input :start_date, label: 'When will your experience begin ?', html5: true %>
                <%= f.input :end_date, label: 'When will it end ?', html5: true %>
                <%= f.submit "Book", class: 'btn btn-flat btn-sm'  %>
              <% end %>
            <% end %>
          </div>
          <div class="info-card">
            <h2 class="mb-4">Your booking info</h2>
            <p id="total_price"></p>
            <p id="duration"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="content-wrapper">
<div class="page">
  <div class="category my-4">
    <div>
      <div id="dashboard">
        <h2 class="mb-4">My dashboard</h2>
        <div class="two-columns-page">
          <div>
            <h4 class="mb-5">My Creatures</h4>
              <% if current_user.creatures.empty? %>
                <div style="opacity: 0.7;">
                  <p>You don't have any creature to rent yet ? Don't hesitate to add one by clicking the button below</p>
                  <%= link_to 'add a creature', new_creature_path, class: "btn btn-flat btn-sm", :style=>'width: 210px;' %>
                </div>
              <% else %>
                <div class="two-columns-cards" style="padding-top: 0;">
                    <% @creatures.each do |creature| %>
                        <% if creature.profile_pic.attached? %>
                          <div class="card-creature">
                            <%= image_tag creature.profile_pic %>
                            <h1><%= creature.name %></h1>
                            <p><%= creature.description %></p>
                            <div class="card-bottom">
                              <%= link_to creature_path(creature), :style=>'width: 50px; color: gray', method: :delete, data: { confirm: "Are you sure?" } do %>
                                <i class="fas fa-trash booking-delete"></i>
                              <% end %>
                              <h1><%= creature.price_per_day %>$ <small>per day</small></h1>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                </div>
              <% end %>
          </div>
          <div>
            <div>
              <h4 class="mb-5">Your bookings</h4>
              <% if current_user.bookings.empty? %>
                <div style="opacity: 0.7;">
                  <p>You haven't make a booking yet ? Don't hesitate to make one by clicking the button below</p>
                  <%= link_to 'book an experience', creatures_index_path, class: "btn btn-flat btn-sm", :style=>'width: 255px;' %>
                </div>
              <% else %>
                <% @bookings.each do |booking| %>
                  <div class="booking-cards">
                    <div class="card-product">
                      <%= image_tag booking.creature.profile_pic %>
                      <%= link_to creature_path(booking.creature) do %>
                        <div class="card-product-infos">
                          <% finish = Date.parse(booking.end_date.to_s()); %>
                          <% start = Date.parse(booking.start_date.to_s()); %>
                          <% days = (finish - start).to_i %>
                          <% days_left = (start - Date.today).to_i %>
                          <h2><%= booking.creature.name %> and you - <small><em>in <%= days_left %> days</em></small></h2>
                          <p>Your experience with <%= booking.creature.name %> is booked for <%= days %> days.</p>
                          <p style="opacity: 0;">.</p>
                          <h6 class="booking-total">Total: <%= booking.creature.price_per_day *  days %>$</h6>
                        </div>
                      <% end %>
                      <div class="card-product-icons">
                        <%= link_to booking_path(booking), method: :delete, data: { confirm: "Are you sure?" } do %>
                          <i class="fas fa-trash booking-delete"></i>
                        <% end %>
                        <%= link_to edit_booking_path(booking) do %>
                          <i class="fas fa-edit booking-edit"></i>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/bookings/new.html.erb
<h1>New Bookings </h1>

<% simple_form_for [@creature, @booking] do |f| %>
  <%= f.input :start_date, as: :bootstrap_datepicker %>
  <%= f.input :end_date, as: :bootstrap_datepicker %>
  <%= f.button :submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/creatures/_info_window.html.erb
<h4><%= creature.name %></h2>
<p><%= creature.address%></p>

app/views/creatures/create.html.erb
<% if policy(Creature).create? %>
  <%= link_to "New Creature", new_creature_path %>
<% end %>

app/views/creatures/index.html.erb
<div class="page">
  <div class="category my-4">
    <div>
      <h2>Browse our magical creatures</h2>
      <div class="two-columns-page">
        <div class="two-columns-cards">
          <% @creatures.each do |creature| %>
            <%= link_to creature_path(creature) do %>
              <div class="card-creature">
                <%if creature.profile_pic.attached?%>
                  <%= image_tag creature.profile_pic %>
                  <h1><%= creature.name %> the <%= creature.species %></h1>
                  <p><%= creature.description %></p>
                <%end%>
                <div class="card-bottom">
                  <h1><%= creature.rating %> ⭐️</h1>
                  <h1><%= creature.price_per_day %>$ <small>per day</small></h1>
                </div>
              </div>
            <%end%>
          <% end %>
        </div>
        <div>
          <div id="map"
                class="my-4"
                style="width: 600px; height: 90vh"
                data-markers="<%= @markers.to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/creatures/new.html.erb
<div class="page">
    <%= simple_form_for [@creature] do |f| %>
        <%= f.input :name %>
        <%= f.input :species%>
        <%= f.input :age%>
        <%= f.input :address%>
        <%= f.input :power, collection: ["good-luck","flying","dark-power","magic"]%>
        <%= f.input :rating%>
        <%= f.input :profile_pic, as: :file%>
        <%= f.input :description%>
        <%= f.input :price_per_day%>
        <%= f.submit "Submit creature", class: "btn btn-index white-button-words" %>
    <% end %>
    <br>
<div>

app/views/creatures/search.html.erb
<div class="page">
  <div class="category my-4">
    <div>
      <h2>Discover new powers</h2>
      <div class="two-columns-page">
        <div class="two-columns-cards">
          <% @creatures.each do |creature| %>
            <%= link_to creature_path(creature) do %>
              <div class="card-creature">
                <%= image_tag creature.profile_pic %>
                <h1><%= creature.name %> the <%= creature.species %></h1>
                <p><%= creature.description %></p>
                <div class="card-bottom">
                  <h1><%= creature.rating %> ⭐️</h1>
                  <h1><%= creature.price_per_day %>$ <small>per day</small></h1>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <div>
          <div id="map"
                class="my-4"
                style="width: 600px; height: 90vh"
                data-markers="<%= @markers.to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/creatures/search_species.html.erb
<div class="page">
  <div class="category my-4">
    <div>
      <h2>Discover our friendliest friends</h2>
      <div class="two-columns-page">
        <div class="two-columns-cards">
          <% @creatures.each do |creature| %>
            <%= link_to creature_path(creature) do %>
              <div class="card-creature">
                <%= image_tag creature.profile_pic %>
                <h1><%= creature.name %> the <%= creature.species %></h1>
                <p><%= creature.description %></p>
                <div class="card-bottom">
                  <h1><%= creature.rating %> ⭐️</h1>
                  <h1><%= creature.price_per_day %>$ <small>per day</small></h1>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        <div>
          <div id="map"
                class="my-4"
                style="width: 600px; height: 90vh;"
                data-markers="<%= @markers.to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/creatures/show.html.erb
<div class="page">
  <div class="category">
    <div>
      <h2 class="my-4">Book your experience with <%= @creature.name %></h2>
      <div class="two-columns-page">
        <div class="left-block">
          <div class="card-product" style="height: 140px;">
            <%= image_tag @creature.profile_pic, :style => "height: 100%; width: 140px;" %>
            <div class="card-product-infos">
              <h2><%= @creature.name %> the <%= @creature.species %></h2>
              <p><%= @creature.description %></p>
              <p style="opacity: 0;">.</p>
              <div class="bottom" style="display:flex; justify-content: space-between;">
                <p><%= @creature.rating %> ⭐️</p>
                <p id="creature_price"><%= @creature.price_per_day %>$ <small>per day</small></p>
              </div>
            </div>
          </div>
          <div id="map"
                  class="my-4"
                  style="width: 600px; height: 400px; border-radius: 7px;"
                  data-markers="<%= @markers.to_json %>"
                  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          </div>
        <div class="right-block">
          <div>
            <% if policy(@booking).new? %>
              <%= simple_form_for [@creature, @booking] do |f| %>
                <%= f.input :start_date, as: :string, label: 'When will your experience begin ?', required: false, input_html: {class: "datepicker"} %>
                <%= f.input :end_date, as: :string, label: 'When will it end ?', required: false, input_html: {class: "datepicker"} %>
                <%= f.button :submit, "Book", class: "btn btn-flat btn-sm" %>
              <% end %>
            <% end %>
          </div>
          <div class="info-card">
            <h2 class="mb-4">Your booking info</h2>
            <p id="total_price"></p>
            <p id="duration"></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534447677768-be436bb09401?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1371&q=80);">
  <div class="container-banner">
    <div class="banner-top-div">
      <h1>Do you <strong>believe</strong> in <strong>magic</strong>?</h1>
      <p>Discover the real world of fanstasy.</p>
    </div>
    <div class="banner-bottom-div">
      <div class="search-element">
        <%= form_tag creatures_index_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            id: "address-input",
            placeholder: "Type your location here...."
          %>
      </div>
          <%= submit_tag "✦", class: "search-button" %>
        <% end %>
    </div>
  </div>
</div>

app/views/pages/_navbar-nonhome.html.erb
<% if user_signed_in? %>
<div class="navbar navbar-inverse sticky-top navbar-light navbar-expand-sm navbar-lewagon">
    <div class="logo-brand">
    <%= link_to root_path, class: "navbar-brand" do %>
      <p class="non-home-p"><%= image_tag "monster-logo.png" %> RentCreatures</p>
    <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else%>
            <%= image_tag "wand.jpg" , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <%end%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", bookings_path, class: "dropdown-item"%>
              <%=link_to "Create a Creature", new_creature_path, class: "dropdown-item"%>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
        </li>
      </ul>
    </div>
</div>
<% else %>
  <div class="navbar navbar-inverse sticky-top navbar-light navbar-expand-sm navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <div class="logo-brand">
        <p class="p-logo"><%= image_tag "monster-logo.png" %> RentCreatures</p>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/pages/_navbar.html.erb
<% if user_signed_in? %>
<div class="navbar navbar-inverse navbar-trans sticky-top navbar-light navbar-expand-sm navbar-fixed-top">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="logo-brand">
      <p class="p-logo"><%= image_tag "monster-logo.png" %> RentCreatures</p>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else%>
            <%= image_tag "wand.jpg" , class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
          <%end%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", bookings_path, class: "dropdown-item"%>
              <%=link_to "Create a Creature", new_creature_path, class: "dropdown-item"%>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            </div>
        </li>
      </ul>
    </div>
</div>
<% else %>
  <div class="navbar navbar-inverse navbar-trans sticky-top navbar-light navbar-expand-sm navbar-fixed-top">
    <%= link_to "#", class: "navbar-brand" do %>
      <div class="logo-brand">
      <p class="p-logo"><%= image_tag "monster-logo.png" %> RentCreatures</p>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<%= render "pages/navbar" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534447677768-be436bb09401?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1371&q=80);">
  <div class="container-banner">
    <div class="banner-top-div">
      <h1><span id="banner-typed-text"></span></strong></h1>
      <p>Discover the real world of fanstasy.</p>
    </div>
    <div class="banner-bottom-div">
      <div class="search-element">
        <%= form_tag creatures_index_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            id: "address-input",
            placeholder: "Type your location here...."
          %>
      </div>
          <%= submit_tag "✦", class: "search-button" %>
        <% end %>
    </div>
  </div>
</div>
<div class="page">
  <div class="category my-4">
    <div>
      <h2 class="my-4">Discover new powers</h2>
      <div class="cards">
        <%= link_to creatures_search_path(power: "flying") do %>
          <div class="card-power">
            <%= image_tag "flying.jpg" %>
            <div class="card-product-infos">
              <h2>Fly</h2>
              <p>Go abroad on the <strong>comfiest creatures</strong></p>
            </div>
          </div>
        <% end %>
        <%= link_to creatures_search_path(power: "dark-power") do %>
          <div class="card-power">
            <%= image_tag "demon.jpg" %>
            <div class="card-product-infos">
              <h2>Dark powers</h2>
              <p>Curse your <strong>worst enemy</strong> with the help of our demons</p>
            </div>
          </div>
        <% end %>
        <%= link_to creatures_search_path(power: "good-luck") do %>
          <div class="card-power">
            <%= image_tag "magic.jpg" %>
            <div class="card-product-infos">
              <h2>Luck</h2>
              <p>Get the <strong>best luck</strong> for your projects</p>
            </div>
          </div>
        <% end %>
        <%= link_to creatures_search_path(power: "magic") do %>
          <div class="card-power">
            <%= image_tag "wizard.jpg" %>
            <div class="card-product-infos">
              <h2>Wichcraft</h2>
              <p>Become <strong>Harry Potter </strong>for a day</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="category my-4">
    <div>
      <h2 class="my-4">Meet our friendliest creatures</h2>
        <div class="cards">
          <%= link_to creatures_shsp_path(species: "dragon") do %>
            <div class="card-type" style="background-image: url(<%= image_path('dragon.jpg') %>)">
              <h1>Dragons</h1>
            </div>
          <% end %>
          <%= link_to creatures_shsp_path(species: "elf") do %>
            <div class="card-type" style="background-image: url(<%= image_path('elf.jpg') %>)">
              <h1>Elves</h1>
            </div>
          <% end %>
          <%= link_to creatures_shsp_path(species: "demon") do %>
            <div class="card-type" style="background-image: url(<%= image_path('evil.jpg') %>)">
              <h1>Demons</h1>
            </div>
          <% end %>
          <%= link_to creatures_shsp_path(species: "wizard") do %>
            <div class="card-type" style="background-image: url(<%= image_path('wand.jpg') %>)">
              <h1>Wizards & Witches</h1>
            </div>
          <% end %>
        </div>
    </div>
  </div>
    <div class="big-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('big-card.jpg') %>)">
      <h1 class="my-3">Book your next experience now</h1>
      <button class="btn btn-index"><a href="/creatures/index">See all the creatures</a></button>
    </div>
  </div>
</div>
<div class="page">
  <div class="category my-4">
    <div>
      <h2 class="my-4">Our best recommandations now</h2>
      <div class="cards">
        <% @sample_creature.each do |creature| %>
          <%= link_to creature_path(creature) do %>
            <div class="card-creature">
              <% if creature.profile_pic != nil %>
                <%= image_tag creature.profile_pic %>
              <% else %>
                <%= image_tag "monster-logo.png" %>
              <% end %>
                <h1> <%= creature.name %> the <%= creature.species %> </h1>
                <p> <%= creature.description %> </p>
              <div class="card-bottom">
                <h1> <%= creature.rating %>⭐️</h1>
                <h1> <%= creature.price_per_day %> <small>per day</small></h1>
              </div>
            </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>